### ISSUE TITLE
Crash in logging service

### ISSUE THREAD

**Issue by sfa-cr** [comicrelief/lambda-wrapper#66]
After updating packages yesterday the Grants API fails on every request with the following stacktrace. I haven't `yarn install`ed in a while so not sure how recently this problem started.

```
TypeError: Cannot read property 'metric' of undefined
    at LoggerService.metric (node_modules/@comicrelief/lambda-wrapper/dist/Service/Logger.service.js:183:48)
    at instance (node_modules/@comicrelief/lambda-wrapper/dist/Wrapper/LambdaWrapper.js:44:14)
    at Promise (node_modules/serverless-offline/src/ApiGateway.js:946:17)
    at new Promise (<anonymous>)
    at handler (node_modules/serverless-offline/src/ApiGateway.js:540:16)
    at module.exports.internals.Manager.execute (node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (node_modules/@hapi/hapi/lib/request.js:312:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by seb-cr** [comment]
Pretty sure this was fixed by #69
